spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

otl:
  url:
    server: 'http://localhost:8080'
    live-api: 'http://10.41.3.86'
    push: 'http://10.41.4.126'

---
spring:
  profiles: prod
  rabbitmq:
    host: 10.41.0.142
    port: 5672
    username: rabbitmq
    password: rabbitmq
otl:
  url:
    server: 'http://sports.naver.com'
    live-api: 'http://10.41.0.142'
    push: '45.119.146.240'
